universe   = vanilla
executable = /bin/bash
getenv     = True

arguments  = ./scripts/david/run_token_collapse.sh $(cfg_tag) $(ckpt_path) $(Cluster)_$(Process)

request_cpus   = 4
request_memory = 48GB
request_gpus   = 1
requirements   = regexp("H100", TARGET.CUDADeviceName) && !regexp("i203", TARGET.Machine)

log    = condor_logs/token_collapse_$(cfg_tag)_$(Cluster)_$(Process).log
output = condor_logs/token_collapse_$(cfg_tag)_$(Cluster)_$(Process).out
error  = condor_logs/token_collapse_$(cfg_tag)_$(Cluster)_$(Process).err

queue cfg_tag, ckpt_path from (
  16l-preln-lr2e3, /fast/wangk/ckpt/depthbench/pretrain-llama-350M-L16-base-lr2e-3/step7600
  20l-preln-lr2e3, /fast/wangk/ckpt/depthbench/pretrain-llama-350M-L20-base-lr2e-3/step7600
  24l-preln-lr2e3, /fast/wangk/ckpt/depthbench/pretrain-llama-350M-L24-base-lr2e-3/step7600
  26l-preln-lr2e3, /fast/wangk/ckpt/depthbench/pretrain-llama-350M-L26-base-lr2e-3/step7600
  28l-preln-lr2e3, /fast/wangk/ckpt/depthbench/pretrain-llama-350M-L28-base-lr2e-3/step7600
  30l-preln-lr2e3, /fast/wangk/ckpt/depthbench/pretrain-llama-350M-L30-base-lr2e-3/step7600
  32l-preln-lr2e3, /fast/wangk/ckpt/depthbench/pretrain-llama-350M-L32-base-lr2e-3/step7600
)
