universe = vanilla
initialdir = /fast/wliu/yy/DepthBench_workspace/DepthBench
executable = /bin/bash
arguments = /fast/wliu/yy/DepthBench_workspace/DepthBench/scripts/run_mhc_static_350m_8gpu.sh
request_cpus = 32
request_memory = 128000
request_gpus = 8
requirements = (TARGET.CUDAGlobalMemoryMb >= 80000) && (TARGET.CUDACapability >= 8.0) && regexp("H100", TARGET.CUDADeviceName) && (TARGET.Machine != "i103.internal.cluster.is.localnet")
environment = "LEARNING_RATE=2e-3 DEVICE_TRAIN_MICROBATCH_SIZE=8 MASTER_PORT=35152 RUN_NAME=pretrain-llama-350M-mhc-static-s4-lr2e-3 SAVE_FOLDER=/fast/wliu/yy/DepthBench_workspace/DepthBench/ckpt/depthbench/pretrain-llama-350M-mhc-static-s4-lr2e-3"
output = /fast/wliu/yy/DepthBench_workspace/DepthBench/logs/condor_train_350m_mhc_static_lr2e3_8gpu.$(ClusterId).$(ProcId).out
error = /fast/wliu/yy/DepthBench_workspace/DepthBench/logs/condor_train_350m_mhc_static_lr2e3_8gpu.$(ClusterId).$(ProcId).err
log = /fast/wliu/yy/DepthBench_workspace/DepthBench/logs/condor_train_350m_mhc_static_lr2e3_8gpu.$(ClusterId).$(ProcId).log
queue
