universe = vanilla
initialdir = /fast/wliu/yy/DepthBench_workspace/DepthBench
executable = /bin/bash
arguments = /fast/wliu/yy/DepthBench_workspace/DepthBench/scripts/run_mhc_linear_350m_8gpu.sh
request_cpus = 32
request_memory = 128000
request_gpus = 8
requirements = (TARGET.CUDAGlobalMemoryMb >= 180000) && (TARGET.CUDACapability >= 10.0) && regexp("B200", TARGET.CUDADeviceName)
environment = "LEARNING_RATE=1e-3 DEVICE_TRAIN_MICROBATCH_SIZE=4 MASTER_PORT=35261 RUN_NAME=pretrain-llama-350M-mhc-linear-s4-lr1e-3-b200 SAVE_FOLDER=/fast/wliu/yy/DepthBench_workspace/DepthBench/ckpt/depthbench/pretrain-llama-350M-mhc-linear-s4-lr1e-3-b200 SWANLAB_TAGS=350M_mhc_linear_tanh_false_8gpu_b200_s4_fineweb-edu-100bt"
output = /fast/wliu/yy/DepthBench_workspace/DepthBench/logs/condor_train_350m_mhc_linear_lr1e3_8gpu_b200.$(ClusterId).$(ProcId).out
error = /fast/wliu/yy/DepthBench_workspace/DepthBench/logs/condor_train_350m_mhc_linear_lr1e3_8gpu_b200.$(ClusterId).$(ProcId).err
log = /fast/wliu/yy/DepthBench_workspace/DepthBench/logs/condor_train_350m_mhc_linear_lr1e3_8gpu_b200.$(ClusterId).$(ProcId).log
queue
